### ISSUE TITLE
gallery_test.py broken

### ISSUE THREAD

**Issue by jonas-schmitt** [hrittich/lfa-lab#1]
This particular test seems to be broken:
```python
======================================================================
ERROR: test_fw_restriction_2 (gallery_test.GalleryTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "lfa-lab/test/gallery_test.py", line 62, in test_fw_restriction_2
    s = fw_restriction_stencil(grid)
TypeError: fw_restriction_stencil() takes exactly 2 arguments (1 given)

======================================================================
ERROR: test_fw_restriction_3 (gallery_test.GalleryTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "lfa-lab/test/gallery_test.py", line 74, in test_fw_restriction_3
    s = fw_restriction_stencil(grid)
TypeError: fw_restriction_stencil() takes exactly 2 arguments (1 given)

======================================================================
ERROR: test_ml_interpolation_2 (gallery_test.GalleryTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "lfa-lab/test/gallery_test.py", line 29, in test_ml_interpolation_2
    s = ml_interpolation_stencil(grid)
TypeError: ml_interpolation_stencil() takes exactly 2 arguments (1 given)

======================================================================
ERROR: test_ml_interpolation_3 (gallery_test.GalleryTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "lfa-lab/test/gallery_test.py", line 40, in test_ml_interpolation_3
    s = ml_interpolation_stencil(grid)
TypeError: ml_interpolation_stencil() takes exactly 2 arguments (1 given)

----------------------------------------------------------------------
```

**Comment by hrittich** [comment]
Thank you for pointing that out. Should be fixed by commit f97080a26ef5c70b15e605c5f5bbf33e244e8f9c .
